import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./lib/header";
import "bootstrap/dist/css/bootstrap.min.css";
import Footer from "./lib/footer";
import { cookies } from "next/headers";
import { decrypt } from "./lib/auth/session";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className="flex-column min-vh-100 d-flex bg-white">
        <Header />
        {children}
        <Footer />

        <script src="https://cdn.jsdelivr.net/npm/react/umd/react.production.min.js"></script>

        <script src="https://cdn.jsdelivr.net/npm/react-dom/umd/react-dom.production.min.js"></script>

        <script src="https://cdn.jsdelivr.net/npm/react-bootstrap@next/dist/react-bootstrap.min.js"></script>
      </body>
    </html>
  );
}
